org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=babycubeblocks
mod.name=Baby Sulfur Cube Blocks
mod.group=net.mat0u5
mod.version=1.1.0
mod.version_prefix=
mod.version_suffix=
mod.authors=Mat0u5
mod.contributors=
mod.license=MIT
mod.description=Allows baby sulfur cubes to have blocks too!
mod.sources_url=https://github.com/Mat0u5/BabySulfurCubeBlocks
mod.homepage_url=https://github.com/Mat0u5/BabySulfurCubeBlocks
mod.issues_url=https://github.com/Mat0u5/BabySulfurCubeBlocks/issues
mod.discord_url=https://discord.gg/QWJxfb4zQZ

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]

# Publishing
publish.dryrun=false

publish.modrinth.id=qPVX68Lb
publish.curseforge.id=1602662

publish.modrinth=true
publish.curseforge=true
publish.github=true
publish.discord=false

publish.release.fabric=stable
publish.release.neoforge=stable
publish.release.forge=stable

publish.github.prerelease=false
publish.discord.dev=false

publish.github.branch=main
publish.github.target=Mat0u5/BabySulfurCubeBlocks
